name: corona
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: http://www.igindo.com
author: Frank <frank@igindo.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  source_gen: ^0.6.0

dev_dependencies:
  build: any
  build_runner: ^0.3.4
  test: ^0.12.24
  build_test: ^0.6.3
  glob: any
