name: corona
description: A lens implementation, strongly typed, with a build step.
version: 0.2.0
homepage: http://www.igindo.com
author: Frank <frank@igindo.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
  build: ^1.0.2
  source_gen: ^0.9.2
  build_runner: ^1.1.2
  build_test: ^0.10.3
  glob: ^1.1.5
  corona_core:
    git: git@github.com:frankpepermans/corona_core.git

dependency_overrides:
  corona_core:
    path: ../../../igindo/dart/corona_core
